# Generated by Django 5.2.4 on 2025-07-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_mentorshiprequest_mentee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='interests',
            field=models.TextField(default='General mentoring'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='location',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
