# Generated by Django 5.2.4 on 2025-07-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_mentorprofile_interests_mentorprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menteeprofile',
            name='learning_interests',
            field=models.CharField(blank=True, help_text='e.g., Python, Data Science', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorshipassignment',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_assignments', to='mentorship.menteeprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshipassignment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='mentorship.mentorprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='mentorship.menteeprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='mentorship.mentorprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
