# Generated by Django 5.2.4 on 2025-07-17 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_alter_menteeprofile_learning_interests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipassignment',
            name='mentorship_request',
            field=models.OneToOneField(blank=True, help_text='The request that led to this assignment (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='mentorship.mentorshiprequest'),
        ),
        migrations.AlterField(
            model_name='mentorshipassignment',
            name='mentee',
            field=models.OneToOneField(help_text='The mentee who is assigned a mentor.', on_delete=django.db.models.deletion.CASCADE, related_name='current_assignment', to='mentorship.menteeprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshipassignment',
            name='mentor',
            field=models.ForeignKey(help_text='The mentor assigned to this mentee.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_mentees', to='mentorship.mentorprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('assigned', 'Assigned')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipassignment',
            unique_together={('mentee', 'assigned_at')},
        ),
    ]
