# Generated by Django 5.2.4 on 2025-07-18 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0005_mentorshipassignment_mentorship_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='location',
        ),
        migrations.AlterUniqueTogether(
            name='mentorshipassignment',
            unique_together={('mentee', 'mentor')},
        ),
        migrations.AddField(
            model_name='mentorshipassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menteeprofile',
            name='learning_interests',
            field=models.CharField(help_text='e.g., Python, Data Science', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='expertise',
            field=models.CharField(help_text='e.g., Web Development, Career Coaching', max_length=255),
        ),
        migrations.AlterField(
            model_name='mentorshipassignment',
            name='mentee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_assignment', to='mentorship.menteeprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshipassignment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_mentees', to='mentorship.mentorprofile'),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mentorshiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.RemoveField(
            model_name='mentorshipassignment',
            name='mentorship_request',
        ),
    ]
