# Generated by Django 5.2.4 on 2025-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_name_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='topic',
            field=models.TextField(blank=True, help_text='A brief description or topic for this chat room.', null=True),
        ),
    ]
